### ISSUE TITLE
key :chapters not found

### ISSUE THREAD

**Issue by haslinger** [PanoptikumIO/pan#25]
Episode import is currently broken:

```
Request: GET /admin/podcasts/delta_import_all                                                                                 
** (exit) an exception was raised:                                                                                            
    ** (KeyError) key :chapters not found in: %{author: %{name: "Ken Ray"}, description: "- iPhone X Waits Improve in US - Ap 
ple Posts Holiday Gift Guide Site - USITC Investigating Patent Infringement Charges Against Apple - Experts Split on Touch ID 
 and Dead Fingers - Fun Fact: Jimmy Iovine Engineered THE Golden Records - Eero - Home wifi that goes anywhere and covers eve 
rywhere! Get free overnight shipping at eero.com with offer code macosken - Power Mac OS Ken through Patreon at Patreon.com/m 
acosken! - Send me an email: info@macosken.com or call (716)780-4080!", duration: "13:12", enclosures: %{"7a27c57e-cad9-11e7- 
a115-525400407794" => %{guid: nil, length: "10131808", type: "audio/mpeg", url: "http://traffic.libsyn.com/macosken/macosken1 
71116.mp3?dest-id=11799"}}, guid: "6f526f093a72a7e3212b2eede74956d6", link: "http://macosken.libsyn.com/mac-os-ken-11162017", 
 publishing_date: ~N[2017-11-16 11:16:30], shownotes: "- iPhone X Waits Improve in US - Apple Posts Holiday Gift Guide Site - 
 USITC Investigating Patent Infringement Charges Against Apple - Experts Split on Touch ID and Dead Fingers - Fun Fact: Jimmy 
 Iovine Engineered THE Golden Records - Eero - Home wifi that goes anywhere and covers everywhere! Get free overnight shippin 
g at eero.com with offer code macosken - Power Mac OS Ken through Patreon at Patreon.com/macosken! - Send me an email: info@m 
acosken.com or call (716)780-4080!", subtitle: "- iPhone X Waits Improve in US - Apple Posts Holiday Gift Guide Site - USITC  
Investigating Patent Infringement Charges Against Apple - Experts Split on Touch ID and Dead Fingers - Fun Fact: Jimmy Iovine 
 Engineered THE Golden Records - Eero - Home wifi...", summary: "iPhone Xs speed up in the states, Apple's gift guide is up,  
and dead fingers &amp; Touch ID.", title: "Mac OS Ken: 11.16.2017"}                                                           
        (pan) lib/pan/parser/episode.ex:109: Pan.Parser.Episode.persist_one/2                                                 
        (pan) lib/pan/parser/episode.ex:61: anonymous fn/3 in Pan.Parser.Episode.persist_many/2                               
        (stdlib) lists.erl:1263: :lists.foldl/3                                                                               
        (pan) lib/pan/parser/episode.ex:60: Pan.Parser.Episode.persist_many/2                                                 
        (pan) lib/pan/parser/persistor.ex:59: Pan.Parser.Persistor.delta_import/2                                             
        (pan) lib/pan/parser/podcast.ex:34: Pan.Parser.Podcast.delta_import/1                                                 
        (pan) lib/pan_web/models/podcast.ex:178: PanWeb.Podcast.delta_import_one/2                                            
        (pan) lib/pan_web/controllers/podcast_controller.ex:324: anonymous fn/3 in PanWeb.PodcastController.delta_import_all/ 
2
```

**Comment by haslinger** [comment]
There is at least one more, I guess:

```
Request: GET /admin/podcasts/delta_import_all                                                                                 
** (exit) an exception was raised:                                                                                            
    ** (KeyError) key :link not found in: %{author: %{name: "Zicht op Maastricht"}, duration: "02:57", enclosures: %{"be806fa 
8-cadb-11e7-8357-525400407794" => %{guid: nil, length: "1403571", type: "audio/mpeg", url: "http://www.zichtopmaastricht.nl/p 
odcast/audio/01-maasbrug.mp3"}}, guid: "http://www.zichtopmaastricht.nl/podcast/archive/pc01_03042008.mp3", publishing_date:  
~N[2008-04-29 11:21:00], subtitle: "Maasbrug", summary: "De westoever van de Maas was in 2005 helemaal vernieuwd. Vanaf de ka 
demuur is de Servaasbrug, of 'Aw Brök', goed te bekijken. Tijdens de werkzaamheden kwam hier de 'eerste boog' van de 13e eeu  
wse brug te voorschijn. Nu loopt daar een voetpad onderdoor. De boog is eigenlijk alles wat over is van de Middeleeuwse stene 
n brug.", title: "01. Maasbrug - Zicht op Maastricht"}                                                                        
        (pan) lib/pan/parser/episode.ex:135: Pan.Parser.Episode.clean_episode/2                                               
        (pan) lib/pan/parser/episode.ex:106: Pan.Parser.Episode.persist_one/2                                                 
        (pan) lib/pan/parser/episode.ex:61: anonymous fn/3 in Pan.Parser.Episode.persist_many/2                               
        (stdlib) lists.erl:1263: :lists.foldl/3                                                                               
        (pan) lib/pan/parser/episode.ex:60: Pan.Parser.Episode.persist_many/2                                                 
        (pan) lib/pan/parser/persistor.ex:59: Pan.Parser.Persistor.delta_import/2                                             
        (pan) lib/pan/parser/podcast.ex:34: Pan.Parser.Podcast.delta_import/1                                                 
        (pan) lib/pan_web/models/podcast.ex:178: PanWeb.Podcast.delta_import_one/2    
```

**Comment by haslinger** [comment]
Two more:  
`** (KeyError) key :contributors not found in:  (pan) lib/pan/parser/episode.ex:110: Pan.Parser.Episode.persist_one/2 `

and 

` ** (KeyError) key :link not found in: (pan) lib/pan/parser/episode.ex:131: Pan.Parser.Episode.clean_episode/2    `

**Comment by haslinger** [comment]
Another one:

```
equest: GET /admin/podcasts/delta_import_all
** (exit) an exception was raised:
    ** (KeyError) key :author not found in: %{description: "Das Beste aus der SWR3-Morningshow, mit Michael Wirbitzky &amp;am
p; Sascha Zeus oder Anneta Politi &amp;amp; Kemal Goga - die wichtigsten Infos und die besten Gags zum Nochmalhören....", du
ration: "12:44", enclosures: %{"447c2b60-cae1-11e7-bf26-525400407794" => %{guid: nil, length: "12244677", type: "audio/mpeg", 
 url: "http://avdlswr-a.akamaihd.net/swr3/sendungen/morningshow/20171116/980233.m.mp3"}}, guid: "swr3.de/podcast/aeXid/458737 
6", link: "https://www.swr3.de/-/id=47308/did=4587376/1038d8w/index.html", publishing_date: ~N[2017-11-16 09:08:53], title: " 
Podcast der SWR3 Morningshow vom 16.11.2017"}                                                                                 
        (pan) lib/pan/parser/episode.ex:113: Pan.Parser.Episode.persist_one/2                                                 
        (pan) lib/pan/parser/episode.ex:61: anonymous fn/3 in Pan.Parser.Episode.persist_many/2                               
        (stdlib) lists.erl:1263: :lists.foldl/3                                                                               
        (pan) lib/pan/parser/episode.ex:60: Pan.Parser.Episode.persist_many/2                                                 
        (pan) lib/pan/parser/persistor.ex:59: Pan.Parser.Persistor.delta_import/2                                             
        (pan) lib/pan/parser/podcast.ex:34: Pan.Parser.Podcast.delta_import/1                                                 
        (pan) lib/pan_web/models/podcast.ex:178: PanWeb.Podcast.delta_import_one/2                                            
        (pan) lib/pan_web/controllers/podcast_controller.ex:324: anonymous fn/3 in PanWeb.PodcastController.delta_import_all/
```

**Comment by haslinger** [comment]
I'm quite confident we got all after 2000+ podcasts update.
