### ISSUE TITLE
Exception notification bug

### ISSUE THREAD

**Issue by haslinger** [PanoptikumIO/pan#42]
```
[error] Postgrex.Protocol (#PID<0.2708.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.16941.4> exited                                                       │
│09:30:18.475 [error] :gen_event handler {Logger.Backends.ExceptionNotification, :exeception_notification} installed in Logger terminating                                                   │
│** (UndefinedFunctionError) function :socket.connect/5 is undefined or private                                                                                                              │
│    (gen_smtp) :socket.connect(:tcp, 'localhost', 25, [:binary, {:packet, :line}, {:keepalive, true}, {:active, false}], 5000)                                                              │
│    (gen_smtp) /home/stefan/phoenix_deployment/pan/deps/gen_smtp/src/gen_smtp_client.erl:533: :gen_smtp_client.connect/2                                                                    │
│    (gen_smtp) /home/stefan/phoenix_deployment/pan/deps/gen_smtp/src/gen_smtp_client.erl:198: :gen_smtp_client.do_smtp_session/3                                                            │
│    (gen_smtp) /home/stefan/phoenix_deployment/pan/deps/gen_smtp/src/gen_smtp_client.erl:143: :gen_smtp_client.try_smtp_sessions/4                                                          │
│    (bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:77: Bamboo.SMTPAdapter.deliver/2                                                                                                      │
│    (bamboo) lib/bamboo/mailer.ex:123: Bamboo.Mailer.deliver_now/3                                                                                                                          │
│    (pan) lib/logger/backends/exception_notification.ex:18: Logger.Backends.ExceptionNotification.handle_event/2                                                                            │
│    (stdlib) gen_event.erl:577: :gen_event.server_update/4                                                                                                                                  │
│Last message: {:error, #PID<0.2520.0>, {Logger, ["Postgrex.Protocol", 32, 40, "#PID<0.2708.0>", ") disconnected: " | "** (DBConnection.ConnectionError) client #PID<0.16941.4> exited"], {{2│
│09:30:18.478 [error] GenServer #PID<0.9262.4> terminating                                                                                                                                   │
│** (stop) {:EXIT, {:undef, [{:socket, :connect, [:tcp, 'localhost', 25, [:binary, {:packet, :line}, {:keepalive, true}, {:active, false}], 5000], []}, {:gen_smtp_client, :connect, 2, [file│
│Last message: {:gen_event_EXIT, {Logger.Backends.ExceptionNotification, :exeception_notification}, {:EXIT, {:undef, [{:socket, :connect, [:tcp, 'localhost', 25, [:binary, {:packet, :line},
```

**Comment by haslinger** [comment]
Fixed by package update.
